// Plant Disease Knowledge Base
// Based on PlantVillage dataset (38 classes, 54,303 images, 14 crop species)
// Extended with Bangladesh-specific crops (Rice, Jute, Brinjal) from BARI/BRRI/DAE
//
// Source: Hughes, D.P., Salathé, M. "An open access repository of images on plant health
//         to enable the development of mobile disease diagnostics." arXiv:1511.08060 (2015)
//         https://github.com/spMohanty/PlantVillage-Dataset

export interface DiseaseRecord {
  id: string;
  cropName: string;
  cropNameBn: string;
  diseaseName: string;
  diseaseNameBn: string;
  className: string;       // PlantVillage class name (or custom for BD crops)
  isHealthy: boolean;
  symptoms: string[];
  symptomsBn: string[];
  cause: string;
  causeBn: string;
  treatment: string[];
  treatmentBn: string[];
  prevention: string[];
  preventionBn: string[];
  severity: 'low' | 'moderate' | 'high' | 'critical';
  source: string;
  sourceUrl: string;
}

export const PLANT_DISEASES: DiseaseRecord[] = [
  // ─── TOMATO (10 classes) ─────────────────────────────────────
  {
    id: 'pv_tomato_bacterial_spot',
    cropName: 'Tomato', cropNameBn: 'টমেটো',
    diseaseName: 'Bacterial Spot', diseaseNameBn: 'ব্যাকটেরিয়াল স্পট',
    className: 'Tomato___Bacterial_spot', isHealthy: false,
    symptoms: ['Small, dark, water-soaked spots on leaves', 'Spots may have yellow halos', 'Fruit develops raised, scab-like lesions'],
    symptomsBn: ['পাতায় ছোট, গাঢ়, জলছাপ দাগ', 'দাগের চারপাশে হলুদ বলয়', 'ফলে উঁচু, খোসপাঁচড়ার মতো ক্ষত'],
    cause: 'Xanthomonas campestris pv. vesicatoria bacteria',
    causeBn: 'জ্যান্থোমোনাস ক্যাম্পেস্ট্রিস ব্যাকটেরিয়া',
    treatment: ['Apply copper-based bactericide (Bordeaux mixture 1%)', 'Remove and destroy infected plant parts', 'Avoid overhead irrigation'],
    treatmentBn: ['কপার-ভিত্তিক ব্যাকটেরিসাইড প্রয়োগ করুন (বোর্দো মিশ্রণ ১%)', 'আক্রান্ত অংশ কেটে ধ্বংস করুন', 'উপর থেকে সেচ দেওয়া বন্ধ করুন'],
    prevention: ['Use certified disease-free seeds', 'Practice crop rotation (3-year)', 'Avoid working in wet fields'],
    preventionBn: ['প্রত্যয়িত রোগমুক্ত বীজ ব্যবহার করুন', '৩ বছরের শস্য পর্যায় অনুসরণ করুন', 'ভেজা ক্ষেতে কাজ করবেন না'],
    severity: 'moderate', source: 'PlantVillage + BARI', sourceUrl: 'https://plantvillage.psu.edu/topics/tomato/infos',
  },
  {
    id: 'pv_tomato_early_blight',
    cropName: 'Tomato', cropNameBn: 'টমেটো',
    diseaseName: 'Early Blight', diseaseNameBn: 'আর্লি ব্লাইট',
    className: 'Tomato___Early_blight', isHealthy: false,
    symptoms: ['Concentric ring-pattern (target-like) brown spots on lower leaves', 'Leaves yellow and drop prematurely', 'Dark lesions on stems near soil line'],
    symptomsBn: ['নিচের পাতায় গোলাকার বাদামী দাগ (লক্ষ্যবোর্ডের মতো)', 'পাতা হলুদ হয়ে ঝরে পড়ে', 'মাটির কাছের কাণ্ডে কালো ক্ষত'],
    cause: 'Alternaria solani fungus',
    causeBn: 'অলটারনারিয়া সোলানি ছত্রাক',
    treatment: ['Apply Mancozeb 75WP (2g/L) or Chlorothalonil', 'Remove lower infected leaves', 'Improve air circulation by proper spacing'],
    treatmentBn: ['ম্যানকোজেব ৭৫WP (২গ্রা/লি) বা ক্লোরোথ্যালোনিল প্রয়োগ করুন', 'নিচের আক্রান্ত পাতা সরান', 'সঠিক দূরত্বে চাষ করে বায়ু চলাচল বাড়ান'],
    prevention: ['Mulch around plants to prevent soil splash', 'Water at base, not overhead', 'Rotate with non-solanaceous crops'],
    preventionBn: ['মাটির ছিটকে যাওয়া রোধে গাছের চারপাশে মালচিং করুন', 'গোড়ায় পানি দিন, উপর থেকে নয়', 'সোলানেসি-বহির্ভূত ফসলের সাথে পর্যায় করুন'],
    severity: 'high', source: 'PlantVillage + BARI', sourceUrl: 'https://plantvillage.psu.edu/topics/tomato/infos',
  },
  {
    id: 'pv_tomato_late_blight',
    cropName: 'Tomato', cropNameBn: 'টমেটো',
    diseaseName: 'Late Blight', diseaseNameBn: 'লেট ব্লাইট',
    className: 'Tomato___Late_blight', isHealthy: false,
    symptoms: ['Large, dark, water-soaked lesions on leaves', 'White fuzzy mold on leaf undersides in humid conditions', 'Rapid browning and death of foliage', 'Brown, firm rot on fruit'],
    symptomsBn: ['পাতায় বড়, গাঢ়, জলছাপ ক্ষত', 'আর্দ্র আবহাওয়ায় পাতার নিচে সাদা তুলতুলে ছত্রাক', 'দ্রুত বাদামী হয়ে পাতা মরে যাওয়া', 'ফলে বাদামী, শক্ত পচন'],
    cause: 'Phytophthora infestans oomycete',
    causeBn: 'ফাইটোফথোরা ইনফেস্ট্যান্স',
    treatment: ['Apply Metalaxyl + Mancozeb (Ridomil Gold 68WP at 2g/L)', 'Destroy all infected plants immediately', 'Do not compost infected material'],
    treatmentBn: ['মেটালাক্সিল + ম্যানকোজেব (রিডোমিল গোল্ড ৬৮WP ২গ্রা/লি) প্রয়োগ', 'আক্রান্ত গাছ তৎক্ষণাৎ ধ্বংস করুন', 'আক্রান্ত উপাদান কম্পোস্ট করবেন না'],
    prevention: ['Use resistant varieties', 'Avoid planting near potato fields', 'Ensure good drainage and air flow'],
    preventionBn: ['প্রতিরোধী জাত ব্যবহার করুন', 'আলু ক্ষেতের কাছে চাষ করবেন না', 'ভালো নিষ্কাশন ও বায়ু চলাচল নিশ্চিত করুন'],
    severity: 'critical', source: 'PlantVillage + BARI', sourceUrl: 'https://plantvillage.psu.edu/topics/tomato/infos',
  },
  {
    id: 'pv_tomato_leaf_mold',
    cropName: 'Tomato', cropNameBn: 'টমেটো',
    diseaseName: 'Leaf Mold', diseaseNameBn: 'পাতার ছাতা রোগ',
    className: 'Tomato___Leaf_Mold', isHealthy: false,
    symptoms: ['Pale green to yellow spots on upper leaf surface', 'Olive-green to brown velvety mold on undersides', 'Leaves curl and dry out'],
    symptomsBn: ['পাতার উপরিভাগে হালকা সবুজ থেকে হলুদ দাগ', 'নিচে জলপাই-সবুজ থেকে বাদামী মখমল ছত্রাক', 'পাতা কুঁকড়ে শুকিয়ে যায়'],
    cause: 'Passalora fulva (syn. Cladosporium fulvum) fungus',
    causeBn: 'প্যাসালোরা ফুলভা ছত্রাক',
    treatment: ['Apply fungicide (Chlorothalonil or Mancozeb)', 'Reduce humidity in greenhouse/shelter', 'Remove affected leaves'],
    treatmentBn: ['ছত্রাকনাশক প্রয়োগ করুন (ক্লোরোথ্যালোনিল বা ম্যানকোজেব)', 'গ্রিনহাউসে আর্দ্রতা কমান', 'আক্রান্ত পাতা সরান'],
    prevention: ['Improve ventilation', 'Space plants wider apart', 'Avoid leaf wetness'],
    preventionBn: ['বায়ু চলাচল বাড়ান', 'গাছের মধ্যে বেশি ফাঁক রাখুন', 'পাতা ভেজা রাখবেন না'],
    severity: 'moderate', source: 'PlantVillage', sourceUrl: 'https://plantvillage.psu.edu/topics/tomato/infos',
  },
  {
    id: 'pv_tomato_septoria',
    cropName: 'Tomato', cropNameBn: 'টমেটো',
    diseaseName: 'Septoria Leaf Spot', diseaseNameBn: 'সেপ্টোরিয়া পাতার দাগ',
    className: 'Tomato___Septoria_leaf_spot', isHealthy: false,
    symptoms: ['Small circular spots (2-3mm) with dark borders and gray centers', 'Tiny black dots (pycnidia) visible in centers', 'Starts on lower leaves, spreads upward'],
    symptomsBn: ['ছোট গোলাকার দাগ (২-৩মিমি) গাঢ় সীমানা ও ধূসর কেন্দ্র', 'কেন্দ্রে ক্ষুদ্র কালো বিন্দু দৃশ্যমান', 'নিচের পাতায় শুরু হয়ে উপরে ছড়ায়'],
    cause: 'Septoria lycopersici fungus',
    causeBn: 'সেপ্টোরিয়া লাইকোপার্সিসি ছত্রাক',
    treatment: ['Apply Mancozeb or Chlorothalonil at first sign', 'Remove infected lower leaves', 'Apply fungicide every 7-10 days in wet weather'],
    treatmentBn: ['প্রথম দেখামাত্র ম্যানকোজেব বা ক্লোরোথ্যালোনিল প্রয়োগ', 'আক্রান্ত নিচের পাতা সরান', 'আর্দ্র আবহাওয়ায় ৭-১০ দিন পরপর ছত্রাকনাশক দিন'],
    prevention: ['Mulch to prevent soil splash', 'Staking and pruning for air flow', '3-year crop rotation'],
    preventionBn: ['মাটি ছিটকানো রোধে মালচিং', 'বায়ু চলাচলের জন্য খুঁটি দেওয়া ও ছাঁটাই', '৩ বছরের শস্য পর্যায়'],
    severity: 'moderate', source: 'PlantVillage', sourceUrl: 'https://plantvillage.psu.edu/topics/tomato/infos',
  },
  {
    id: 'pv_tomato_spider_mites',
    cropName: 'Tomato', cropNameBn: 'টমেটো',
    diseaseName: 'Spider Mites (Two-spotted)', diseaseNameBn: 'মাকড়সা মাইট',
    className: 'Tomato___Spider_mites_Two-spotted_spider_mite', isHealthy: false,
    symptoms: ['Fine stippling/yellowing of leaves', 'Tiny webs on leaf undersides', 'Bronze or tan coloring of leaves', 'Leaf drop in severe cases'],
    symptomsBn: ['পাতায় সূক্ষ্ম দাগ/হলুদ হওয়া', 'পাতার নিচে ক্ষুদ্র জাল', 'পাতা ব্রোঞ্জ বা তামাটে রঙ ধারণ', 'গুরুতর ক্ষেত্রে পাতা ঝরে পড়া'],
    cause: 'Tetranychus urticae (two-spotted spider mite)',
    causeBn: 'টেট্রানাইকাস আর্টিকি (দুই-দাগওয়ালা মাকড়সা মাইট)',
    treatment: ['Spray Abamectin 1.8EC or neem oil (5ml/L)', 'Wash leaves with strong water spray', 'Release predatory mites if available'],
    treatmentBn: ['অ্যাবামেক্টিন ১.৮EC বা নিম তেল (৫মিলি/লি) স্প্রে করুন', 'শক্তিশালী পানির স্প্রে দিয়ে পাতা ধুয়ে দিন', 'পাওয়া গেলে শিকারী মাইট ছাড়ুন'],
    prevention: ['Maintain adequate irrigation (mites prefer dry conditions)', 'Avoid excessive nitrogen fertilization', 'Remove weeds that harbor mites'],
    preventionBn: ['পর্যাপ্ত সেচ বজায় রাখুন (মাইট শুষ্ক পরিবেশ পছন্দ করে)', 'অতিরিক্ত নাইট্রোজেন সার দেবেন না', 'মাইট আশ্রয়কারী আগাছা সরান'],
    severity: 'moderate', source: 'PlantVillage', sourceUrl: 'https://plantvillage.psu.edu/topics/tomato/infos',
  },
  {
    id: 'pv_tomato_target_spot',
    cropName: 'Tomato', cropNameBn: 'টমেটো',
    diseaseName: 'Target Spot', diseaseNameBn: 'টার্গেট স্পট',
    className: 'Tomato___Target_Spot', isHealthy: false,
    symptoms: ['Dark brown circular lesions with concentric rings', 'Lesions may coalesce causing large necrotic areas', 'Can affect leaves, stems, and fruit'],
    symptomsBn: ['ঘন বাদামী গোলাকার ক্ষত সমকেন্দ্রিক বলয়সহ', 'ক্ষত একত্রিত হয়ে বড় মৃত এলাকা তৈরি করতে পারে', 'পাতা, কাণ্ড ও ফলে আক্রমণ করতে পারে'],
    cause: 'Corynespora cassiicola fungus',
    causeBn: 'করিনেসপোরা ক্যাসিকোলা ছত্রাক',
    treatment: ['Apply Azoxystrobin or Difenoconazole', 'Remove severely infected plants', 'Ensure proper plant spacing'],
    treatmentBn: ['অ্যাজোক্সিস্ট্রোবিন বা ডাইফেনোকোনাজল প্রয়োগ', 'মারাত্মকভাবে আক্রান্ত গাছ সরান', 'সঠিক গাছের দূরত্ব নিশ্চিত করুন'],
    prevention: ['Use disease-free transplants', 'Avoid overhead irrigation', 'Rotate crops annually'],
    preventionBn: ['রোগমুক্ত চারা ব্যবহার করুন', 'উপর থেকে সেচ পরিহার করুন', 'বার্ষিক শস্য পর্যায় করুন'],
    severity: 'moderate', source: 'PlantVillage', sourceUrl: 'https://plantvillage.psu.edu/topics/tomato/infos',
  },
  {
    id: 'pv_tomato_ylcv',
    cropName: 'Tomato', cropNameBn: 'টমেটো',
    diseaseName: 'Yellow Leaf Curl Virus', diseaseNameBn: 'হলুদ পাতা কোঁকড়ানো ভাইরাস',
    className: 'Tomato___Tomato_Yellow_Leaf_Curl_Virus', isHealthy: false,
    symptoms: ['Severe upward curling and cupping of leaves', 'Leaves become small, crumpled, yellow-green', 'Stunted growth, flower drop', 'Reduced fruit production'],
    symptomsBn: ['পাতা মারাত্মকভাবে উপরে কুঁকড়ে যাওয়া', 'পাতা ছোট, কুঁচকানো, হলদে-সবুজ হওয়া', 'বৃদ্ধি ব্যাহত, ফুল ঝরে পড়া', 'ফল উৎপাদন হ্রাস'],
    cause: 'Tomato Yellow Leaf Curl Virus (TYLCV), transmitted by whitefly (Bemisia tabaci)',
    causeBn: 'টমেটো ইয়েলো লিফ কার্ল ভাইরাস (TYLCV), সাদা মাছি (বেমিসিয়া ট্যাবাসি) দ্বারা বাহিত',
    treatment: ['No cure for viral infection — remove infected plants', 'Control whitefly with Imidacloprid 17.8SL (0.5ml/L)', 'Use yellow sticky traps for whitefly monitoring'],
    treatmentBn: ['ভাইরাস সংক্রমণের কোনো প্রতিকার নেই — আক্রান্ত গাছ সরান', 'ইমিডাক্লোপ্রিড ১৭.৮SL (০.৫মিলি/লি) দিয়ে সাদা মাছি নিয়ন্ত্রণ', 'সাদা মাছি পর্যবেক্ষণে হলুদ আঠালো ফাঁদ ব্যবহার'],
    prevention: ['Use TYLCV-resistant varieties', 'Install insect-proof netting', 'Avoid planting near older infected tomato crops'],
    preventionBn: ['TYLCV-প্রতিরোধী জাত ব্যবহার', 'পোকা-প্রতিরোধী জাল লাগান', 'পুরোনো আক্রান্ত টমেটো ক্ষেতের কাছে চাষ করবেন না'],
    severity: 'critical', source: 'PlantVillage + BARI', sourceUrl: 'https://plantvillage.psu.edu/topics/tomato/infos',
  },
  {
    id: 'pv_tomato_mosaic',
    cropName: 'Tomato', cropNameBn: 'টমেটো',
    diseaseName: 'Tomato Mosaic Virus', diseaseNameBn: 'টমেটো মোজাইক ভাইরাস',
    className: 'Tomato___Tomato_mosaic_virus', isHealthy: false,
    symptoms: ['Mottled light and dark green mosaic pattern on leaves', 'Leaf curling and distortion', 'Stunted plants', 'Reduced and deformed fruits'],
    symptomsBn: ['পাতায় হালকা ও গাঢ় সবুজ মোজাইক প্যাটার্ন', 'পাতা কুঁকড়ানো ও বিকৃতি', 'খাটো গাছ', 'ফল হ্রাস ও বিকৃত'],
    cause: 'Tomato Mosaic Virus (ToMV), spread mechanically via contaminated tools/hands',
    causeBn: 'টমেটো মোজাইক ভাইরাস (ToMV), দূষিত সরঞ্জাম/হাতের মাধ্যমে ছড়ায়',
    treatment: ['No cure — remove and burn infected plants', 'Disinfect tools with 10% bleach solution', 'Wash hands thoroughly between plants'],
    treatmentBn: ['কোনো প্রতিকার নেই — আক্রান্ত গাছ তুলে পুড়িয়ে ফেলুন', '১০% ব্লিচ দ্রবণ দিয়ে সরঞ্জাম জীবাণুমুক্ত করুন', 'গাছে গাছে হাত ভালো করে ধুয়ে নিন'],
    prevention: ['Use ToMV-resistant varieties', 'Disinfect seeds with trisodium phosphate', 'Do not smoke near tomato plants (tobacco carries TMV)'],
    preventionBn: ['ToMV-প্রতিরোধী জাত ব্যবহার', 'ট্রাইসোডিয়াম ফসফেট দিয়ে বীজ জীবাণুমুক্ত করুন', 'টমেটো গাছের কাছে ধূমপান করবেন না (তামাক TMV বহন করে)'],
    severity: 'high', source: 'PlantVillage', sourceUrl: 'https://plantvillage.psu.edu/topics/tomato/infos',
  },
  {
    id: 'pv_tomato_healthy',
    cropName: 'Tomato', cropNameBn: 'টমেটো',
    diseaseName: 'Healthy', diseaseNameBn: 'সুস্থ',
    className: 'Tomato___healthy', isHealthy: true,
    symptoms: ['No visible disease symptoms', 'Uniform green color', 'Normal growth pattern'],
    symptomsBn: ['কোনো রোগের লক্ষণ নেই', 'সমান সবুজ রঙ', 'স্বাভাবিক বৃদ্ধি'],
    cause: 'N/A', causeBn: 'প্রযোজ্য নয়',
    treatment: ['Continue regular maintenance', 'Monitor for early signs of disease'],
    treatmentBn: ['নিয়মিত পরিচর্যা চালিয়ে যান', 'রোগের প্রাথমিক লক্ষণ পর্যবেক্ষণ করুন'],
    prevention: ['Balanced fertilization', 'Proper irrigation', 'Regular field scouting'],
    preventionBn: ['সুষম সার প্রয়োগ', 'সঠিক সেচ', 'নিয়মিত ক্ষেত পরিদর্শন'],
    severity: 'low', source: 'PlantVillage', sourceUrl: 'https://plantvillage.psu.edu/topics/tomato/infos',
  },

  // ─── POTATO (3 classes) ──────────────────────────────────────
  {
    id: 'pv_potato_early_blight',
    cropName: 'Potato', cropNameBn: 'আলু',
    diseaseName: 'Early Blight', diseaseNameBn: 'আর্লি ব্লাইট',
    className: 'Potato___Early_blight', isHealthy: false,
    symptoms: ['Dark brown to black target-like concentric ring lesions', 'Begins on older/lower leaves', 'Yellowing around lesions', 'Tuber lesions are dark, sunken, circular'],
    symptomsBn: ['গাঢ় বাদামী থেকে কালো লক্ষ্যবোর্ডের মতো ক্ষত', 'পুরোনো/নিচের পাতায় শুরু', 'ক্ষতের চারপাশে হলুদ', 'কন্দে গাঢ়, বসা, গোলাকার ক্ষত'],
    cause: 'Alternaria solani fungus',
    causeBn: 'অলটারনারিয়া সোলানি ছত্রাক',
    treatment: ['Spray Mancozeb 75WP (2.5g/L) every 7-10 days', 'Apply Iprodione or Azoxystrobin for severe cases', 'Remove heavily infected foliage'],
    treatmentBn: ['৭-১০ দিন পরপর ম্যানকোজেব ৭৫WP (২.৫গ্রা/লি) স্প্রে', 'গুরুতর ক্ষেত্রে আইপ্রোডায়ন বা অ্যাজোক্সিস্ট্রোবিন', 'মারাত্মকভাবে আক্রান্ত পাতা সরান'],
    prevention: ['Plant certified disease-free seed tubers', 'Maintain proper plant nutrition (especially potassium)', 'Avoid irrigation stress'],
    preventionBn: ['প্রত্যয়িত রোগমুক্ত বীজ আলু ব্যবহার', 'সঠিক পুষ্টি বজায় রাখুন (বিশেষত পটাসিয়াম)', 'সেচের চাপ এড়িয়ে চলুন'],
    severity: 'high', source: 'PlantVillage + BARI', sourceUrl: 'https://plantvillage.psu.edu/topics/potato/infos',
  },
  {
    id: 'pv_potato_late_blight',
    cropName: 'Potato', cropNameBn: 'আলু',
    diseaseName: 'Late Blight', diseaseNameBn: 'লেট ব্লাইট (মড়ক রোগ)',
    className: 'Potato___Late_blight', isHealthy: false,
    symptoms: ['Water-soaked pale green to dark brown lesions spreading rapidly', 'White cottony mold on leaf undersides in moist conditions', 'Entire field can be destroyed within days', 'Reddish-brown granular rot in tubers'],
    symptomsBn: ['জলছাপ হালকা সবুজ থেকে গাঢ় বাদামী ক্ষত দ্রুত ছড়ায়', 'আর্দ্র পরিবেশে পাতার নিচে সাদা তুলতুলে ছত্রাক', 'কয়েক দিনে পুরো মাঠ ধ্বংস হতে পারে', 'কন্দে লালচে-বাদামী দানাদার পচন'],
    cause: 'Phytophthora infestans oomycete',
    causeBn: 'ফাইটোফথোরা ইনফেস্ট্যান্স',
    treatment: ['Apply Metalaxyl + Mancozeb (Ridomil Gold) immediately at first sign', 'Spray Cymoxanil + Mancozeb as alternative', 'Destroy all infected material (do not compost)'],
    treatmentBn: ['প্রথম লক্ষণে তৎক্ষণাৎ মেটালাক্সিল + ম্যানকোজেব (রিডোমিল গোল্ড) প্রয়োগ', 'বিকল্প হিসেবে সাইমোক্সানিল + ম্যানকোজেব স্প্রে', 'সকল আক্রান্ত উপাদান ধ্বংস করুন (কম্পোস্ট করবেন না)'],
    prevention: ['Plant resistant varieties (e.g., BARI Alu-46 Diamant)', 'Keep hill soil ridged to protect tubers', 'Monitor weather — spray preventively when cool + wet'],
    preventionBn: ['প্রতিরোধী জাত চাষ করুন (যেমন, BARI আলু-৪৬ ডায়মন্ড)', 'কন্দ রক্ষায় মাটি উঁচু রাখুন', 'আবহাওয়া পর্যবেক্ষণ — ঠাণ্ডা ও আর্দ্রে প্রতিরোধমূলক স্প্রে'],
    severity: 'critical', source: 'PlantVillage + BARI', sourceUrl: 'https://plantvillage.psu.edu/topics/potato/infos',
  },
  {
    id: 'pv_potato_healthy',
    cropName: 'Potato', cropNameBn: 'আলু',
    diseaseName: 'Healthy', diseaseNameBn: 'সুস্থ',
    className: 'Potato___healthy', isHealthy: true,
    symptoms: ['No visible disease symptoms', 'Uniform green foliage', 'Normal tuber development'],
    symptomsBn: ['কোনো রোগের লক্ষণ নেই', 'সমান সবুজ পাতা', 'স্বাভাবিক কন্দ বিকাশ'],
    cause: 'N/A', causeBn: 'প্রযোজ্য নয়',
    treatment: ['Continue monitoring', 'Maintain balanced nutrition'],
    treatmentBn: ['পর্যবেক্ষণ চালিয়ে যান', 'সুষম পুষ্টি বজায় রাখুন'],
    prevention: ['Regular scouting', 'Certified seed tubers', 'Proper storage conditions'],
    preventionBn: ['নিয়মিত পরিদর্শন', 'প্রত্যয়িত বীজ আলু', 'সঠিক সংরক্ষণ পরিবেশ'],
    severity: 'low', source: 'PlantVillage', sourceUrl: 'https://plantvillage.psu.edu/topics/potato/infos',
  },

  // ─── CORN / MAIZE (4 classes) ────────────────────────────────
  {
    id: 'pv_corn_cercospora',
    cropName: 'Corn (Maize)', cropNameBn: 'ভুট্টা',
    diseaseName: 'Cercospora Leaf Spot / Gray Leaf Spot', diseaseNameBn: 'ধূসর পাতার দাগ',
    className: 'Corn_(maize)___Cercospora_leaf_spot_Gray_leaf_spot', isHealthy: false,
    symptoms: ['Rectangular gray to tan lesions between leaf veins', 'Lesions may coalesce killing entire leaves', 'Starts on lower canopy'],
    symptomsBn: ['পাতার শিরার মধ্যে আয়তাকার ধূসর থেকে তামাটে ক্ষত', 'ক্ষত একত্রিত হয়ে পুরো পাতা মেরে ফেলতে পারে', 'নিচের ক্যানোপিতে শুরু'],
    cause: 'Cercospora zeae-maydis fungus',
    causeBn: 'সার্কোস্পোরা জিয়ে-মেডিস ছত্রাক',
    treatment: ['Apply Propiconazole or Azoxystrobin fungicide', 'Time application at tasseling stage'],
    treatmentBn: ['প্রোপিকোনাজল বা অ্যাজোক্সিস্ট্রোবিন ছত্রাকনাশক প্রয়োগ', 'ট্যাসেলিং পর্যায়ে প্রয়োগের সময় নির্ধারণ'],
    prevention: ['Plant resistant hybrids', 'Tillage to bury residue', 'Crop rotation with non-grass crops'],
    preventionBn: ['প্রতিরোধী হাইব্রিড চাষ', 'অবশিষ্ট মাটিচাপা দিতে চাষ', 'ঘাস-বহির্ভূত ফসলের সাথে পর্যায়'],
    severity: 'high', source: 'PlantVillage', sourceUrl: 'https://plantvillage.psu.edu/topics/corn/infos',
  },
  {
    id: 'pv_corn_rust',
    cropName: 'Corn (Maize)', cropNameBn: 'ভুট্টা',
    diseaseName: 'Common Rust', diseaseNameBn: 'সাধারণ মরিচা রোগ',
    className: 'Corn_(maize)___Common_rust_', isHealthy: false,
    symptoms: ['Small, circular to elongate reddish-brown pustules on both leaf surfaces', 'Pustules break open releasing rusty-brown spores', 'Severe infection causes premature leaf death'],
    symptomsBn: ['পাতার উভয় পৃষ্ঠে ছোট, গোলাকার থেকে লম্বাটে লালচে-বাদামী পুঁজ', 'পুঁজ ফেটে মরচে-বাদামী স্পোর ছড়ায়', 'গুরুতর সংক্রমণে পাতা অকালে মরে যায়'],
    cause: 'Puccinia sorghi fungus',
    causeBn: 'পুচিনিয়া সরঘি ছত্রাক',
    treatment: ['Apply Mancozeb or Propiconazole if caught early', 'Usually no treatment needed for mild infections'],
    treatmentBn: ['প্রথম দিকে ধরা পড়লে ম্যানকোজেব বা প্রোপিকোনাজল প্রয়োগ', 'হালকা সংক্রমণে সাধারণত চিকিৎসার প্রয়োজন নেই'],
    prevention: ['Plant resistant hybrids', 'Early planting to avoid peak spore season', 'Balanced fertilization'],
    preventionBn: ['প্রতিরোধী হাইব্রিড চাষ', 'স্পোর মৌসুমের আগে তাড়াতাড়ি বপন', 'সুষম সার প্রয়োগ'],
    severity: 'moderate', source: 'PlantVillage', sourceUrl: 'https://plantvillage.psu.edu/topics/corn/infos',
  },
  {
    id: 'pv_corn_blight',
    cropName: 'Corn (Maize)', cropNameBn: 'ভুট্টা',
    diseaseName: 'Northern Leaf Blight', diseaseNameBn: 'উত্তরাঞ্চলীয় পাতা ব্লাইট',
    className: 'Corn_(maize)___Northern_Leaf_Blight', isHealthy: false,
    symptoms: ['Long (1-6 inch), elliptical, gray-green to tan lesions', 'Lesions run parallel to leaf veins', 'Can kill significant leaf area reducing yield 30-50%'],
    symptomsBn: ['লম্বা (২.৫-১৫ সেমি), উপবৃত্তাকার, ধূসর-সবুজ থেকে তামাটে ক্ষত', 'ক্ষত পাতার শিরার সমান্তরাল', 'উল্লেখযোগ্য পাতা মেরে ৩০-৫০% ফলন কমাতে পারে'],
    cause: 'Exserohilum turcicum fungus',
    causeBn: 'এক্সসেরোহিলাম টার্সিকাম ছত্রাক',
    treatment: ['Apply Propiconazole or Azoxystrobin + Propiconazole', 'Spray at or before tasseling for best results'],
    treatmentBn: ['প্রোপিকোনাজল বা অ্যাজোক্সিস্ট্রোবিন + প্রোপিকোনাজল প্রয়োগ', 'সর্বোত্তম ফলের জন্য ট্যাসেলিংয়ের আগে বা সময়ে স্প্রে'],
    prevention: ['Resistant hybrids', 'Tillage to decompose residue', '2-year rotation away from corn'],
    preventionBn: ['প্রতিরোধী হাইব্রিড', 'অবশিষ্ট পচানোর জন্য চাষ', 'ভুট্টা থেকে ২ বছরের পর্যায়'],
    severity: 'high', source: 'PlantVillage', sourceUrl: 'https://plantvillage.psu.edu/topics/corn/infos',
  },
  {
    id: 'pv_corn_healthy',
    cropName: 'Corn (Maize)', cropNameBn: 'ভুট্টা',
    diseaseName: 'Healthy', diseaseNameBn: 'সুস্থ',
    className: 'Corn_(maize)___healthy', isHealthy: true,
    symptoms: ['No disease symptoms', 'Uniform green leaves', 'Normal growth'],
    symptomsBn: ['কোনো রোগের লক্ষণ নেই', 'সমান সবুজ পাতা', 'স্বাভাবিক বৃদ্ধি'],
    cause: 'N/A', causeBn: 'প্রযোজ্য নয়',
    treatment: ['Continue standard management'],
    treatmentBn: ['মানসম্মত পরিচর্যা চালিয়ে যান'],
    prevention: ['Regular scouting', 'Balanced nutrition'],
    preventionBn: ['নিয়মিত পরিদর্শন', 'সুষম পুষ্টি'],
    severity: 'low', source: 'PlantVillage', sourceUrl: 'https://plantvillage.psu.edu/topics/corn/infos',
  },

  // ─── PEPPER / CHILI (2 classes) ──────────────────────────────
  {
    id: 'pv_pepper_bacterial_spot',
    cropName: 'Pepper (Bell/Chili)', cropNameBn: 'মরিচ',
    diseaseName: 'Bacterial Spot', diseaseNameBn: 'ব্যাকটেরিয়াল স্পট',
    className: 'Pepper,_bell___Bacterial_spot', isHealthy: false,
    symptoms: ['Small, dark, water-soaked spots on leaves', 'Spots become raised and scab-like on fruit', 'Leaf drop and defoliation in severe cases'],
    symptomsBn: ['পাতায় ছোট, গাঢ়, জলছাপ দাগ', 'ফলে দাগ উঁচু ও খোসপাঁচড়ার মতো হয়', 'গুরুতর ক্ষেত্রে পাতা ঝরে পড়া'],
    cause: 'Xanthomonas euvesicatoria bacteria',
    causeBn: 'জ্যান্থোমোনাস ইউভেসিকেটোরিয়া ব্যাকটেরিয়া',
    treatment: ['Copper hydroxide or copper sulfate sprays', 'Remove and destroy infected plants', 'Avoid working in wet conditions'],
    treatmentBn: ['কপার হাইড্রোক্সাইড বা কপার সালফেট স্প্রে', 'আক্রান্ত গাছ সরিয়ে ধ্বংস', 'ভেজা পরিবেশে কাজ করবেন না'],
    prevention: ['Use disease-free transplants', 'Crop rotation (2-3 years)', 'Drip irrigation instead of overhead'],
    preventionBn: ['রোগমুক্ত চারা ব্যবহার', '২-৩ বছরের শস্য পর্যায়', 'উপর থেকে সেচের বদলে ড্রিপ সেচ'],
    severity: 'moderate', source: 'PlantVillage + BARI', sourceUrl: 'https://plantvillage.psu.edu/topics/pepper/infos',
  },
  {
    id: 'pv_pepper_healthy',
    cropName: 'Pepper (Bell/Chili)', cropNameBn: 'মরিচ',
    diseaseName: 'Healthy', diseaseNameBn: 'সুস্থ',
    className: 'Pepper,_bell___healthy', isHealthy: true,
    symptoms: ['No disease symptoms'], symptomsBn: ['কোনো রোগের লক্ষণ নেই'],
    cause: 'N/A', causeBn: 'প্রযোজ্য নয়',
    treatment: ['Continue standard management'], treatmentBn: ['মানসম্মত পরিচর্যা চালিয়ে যান'],
    prevention: ['Regular monitoring'], preventionBn: ['নিয়মিত পর্যবেক্ষণ'],
    severity: 'low', source: 'PlantVillage', sourceUrl: 'https://plantvillage.psu.edu/topics/pepper/infos',
  },

  // ─── RICE (Bangladesh-specific — from BRRI/BARI/DAE) ─────────
  {
    id: 'bd_rice_blast',
    cropName: 'Rice', cropNameBn: 'ধান',
    diseaseName: 'Rice Blast', diseaseNameBn: 'ব্লাস্ট রোগ',
    className: 'Rice___Blast', isHealthy: false,
    symptoms: ['Diamond/eye-shaped spots with gray center on leaves', 'Neck blast: neck of panicle turns dark brown and breaks', 'Node blast: blackened nodes', 'Severely infected panicles produce empty or chalky grains'],
    symptomsBn: ['পাতায় চোখের আকৃতির ধূসর কেন্দ্রবিশিষ্ট দাগ', 'নেক ব্লাস্ট: শীষের ঘাড় গাঢ় বাদামী হয়ে ভেঙে যায়', 'নোড ব্লাস্ট: গিঁট কালো হয়ে যায়', 'মারাত্মকভাবে আক্রান্ত শীষে চিটা বা চকচকে দানা'],
    cause: 'Magnaporthe oryzae (Pyricularia oryzae) fungus',
    causeBn: 'ম্যাগন্যাপোর্থি ওরাইজি (পাইরিকুলারিয়া ওরাইজি) ছত্রাক',
    treatment: ['Apply Tricyclazole 75WP (0.6g/L) preventively', 'Kasugamycin or Isoprothiolane for neck blast', 'Split nitrogen application — avoid excess nitrogen at booting'],
    treatmentBn: ['ট্রাইসাইক্লাজোল ৭৫WP (০.৬গ্রা/লি) প্রতিরোধমূলকভাবে প্রয়োগ', 'নেক ব্লাস্টে কাসুগামাইসিন বা আইসোপ্রোথিওলেন', 'নাইট্রোজেন ভাগ করে দিন — বুটিং পর্যায়ে অতিরিক্ত নাইট্রোজেন দেবেন না'],
    prevention: ['Use blast-resistant varieties (BRRI dhan28, BRRI dhan58)', 'Balanced fertilization (avoid excess N)', 'Ensure good field drainage'],
    preventionBn: ['ব্লাস্ট-প্রতিরোধী জাত ব্যবহার (ব্রি ধান২৮, ব্রি ধান৫৮)', 'সুষম সার (অতিরিক্ত N এড়িয়ে চলুন)', 'ভালো ক্ষেত নিষ্কাশন নিশ্চিত করুন'],
    severity: 'critical', source: 'BRRI Adhunik Dhaner Chash 2023', sourceUrl: 'http://www.brri.gov.bd',
  },
  {
    id: 'bd_rice_brown_spot',
    cropName: 'Rice', cropNameBn: 'ধান',
    diseaseName: 'Brown Spot', diseaseNameBn: 'বাদামী দাগ রোগ',
    className: 'Rice___Brown_Spot', isHealthy: false,
    symptoms: ['Oval brown spots on leaves, often with gray center', 'Spots on glumes cause grain discoloration', 'Seedling blight in nursery'],
    symptomsBn: ['পাতায় ডিম্বাকৃতি বাদামী দাগ, প্রায়ই ধূসর কেন্দ্র', 'গ্লুমে দাগ দানার রঙ পরিবর্তন করে', 'নার্সারিতে চারা ব্লাইট'],
    cause: 'Bipolaris oryzae (Cochliobolus miyabeanus) fungus, often linked to poor soil nutrition',
    causeBn: 'বাইপোলারিস ওরাইজি ছত্রাক, প্রায়ই দুর্বল মাটি পুষ্টির সাথে সম্পর্কিত',
    treatment: ['Seed treatment with Carbendazim (2g/kg seed)', 'Foliar spray of Mancozeb or Edifenphos', 'Correct potassium and zinc deficiency'],
    treatmentBn: ['কার্বেন্ডাজিম (২গ্রা/কেজি বীজ) দিয়ে বীজ শোধন', 'ম্যানকোজেব বা এডিফেনফস পাতায় স্প্রে', 'পটাসিয়াম ও জিংকের ঘাটতি পূরণ'],
    prevention: ['Use healthy seed', 'Apply balanced NPK + micronutrients', 'Avoid drought stress'],
    preventionBn: ['সুস্থ বীজ ব্যবহার', 'সুষম NPK + অণুপুষ্টি প্রয়োগ', 'খরা চাপ এড়িয়ে চলুন'],
    severity: 'high', source: 'BRRI/DAE', sourceUrl: 'http://www.brri.gov.bd',
  },
  {
    id: 'bd_rice_blight',
    cropName: 'Rice', cropNameBn: 'ধান',
    diseaseName: 'Bacterial Leaf Blight (BLB)', diseaseNameBn: 'পাতা পোড়া রোগ (BLB)',
    className: 'Rice___Bacterial_Leaf_Blight', isHealthy: false,
    symptoms: ['Water-soaked lesions starting from leaf tips and margins', 'Lesions turn yellow then grayish-white as they dry', 'Wavy yellowish margins along leaf edges', 'Milky bacterial ooze from cut leaf in water'],
    symptomsBn: ['পাতার ডগা ও কিনারা থেকে জলছাপ ক্ষত শুরু', 'ক্ষত হলুদ তারপর ধূসর-সাদা হয়ে শুকায়', 'পাতার কিনারায় ঢেউ খেলানো হলুদ সীমানা', 'পানিতে কাটা পাতা থেকে দুধের মতো ব্যাকটেরিয়া ক্ষরণ'],
    cause: 'Xanthomonas oryzae pv. oryzae bacteria',
    causeBn: 'জ্যান্থোমোনাস ওরাইজি ব্যাকটেরিয়া',
    treatment: ['No effective chemical cure — manage culturally', 'Drain excess water from fields', 'Avoid excessive nitrogen'],
    treatmentBn: ['কোনো কার্যকর রাসায়নিক প্রতিকার নেই — চাষাবাদ পদ্ধতিতে ব্যবস্থাপনা', 'ক্ষেত থেকে অতিরিক্ত পানি নিষ্কাশন', 'অতিরিক্ত নাইট্রোজেন পরিহার'],
    prevention: ['Use BLB-resistant varieties (BRRI dhan52, BRRI dhan71)', 'Balanced fertilization', 'Avoid transplanting during storms'],
    preventionBn: ['BLB-প্রতিরোধী জাত ব্যবহার (ব্রি ধান৫২, ব্রি ধান৭১)', 'সুষম সার প্রয়োগ', 'ঝড়ের সময় রোপণ পরিহার'],
    severity: 'critical', source: 'BRRI Adhunik Dhaner Chash 2023', sourceUrl: 'http://www.brri.gov.bd',
  },
  {
    id: 'bd_rice_healthy',
    cropName: 'Rice', cropNameBn: 'ধান',
    diseaseName: 'Healthy', diseaseNameBn: 'সুস্থ',
    className: 'Rice___healthy', isHealthy: true,
    symptoms: ['No visible disease symptoms', 'Uniform green tillers', 'Normal panicle development'],
    symptomsBn: ['কোনো রোগের লক্ষণ নেই', 'সমান সবুজ কুশি', 'স্বাভাবিক শীষ বিকাশ'],
    cause: 'N/A', causeBn: 'প্রযোজ্য নয়',
    treatment: ['Continue regular management'], treatmentBn: ['নিয়মিত পরিচর্যা চালিয়ে যান'],
    prevention: ['Balanced fertilization', 'Proper water management'], preventionBn: ['সুষম সার', 'সঠিক পানি ব্যবস্থাপনা'],
    severity: 'low', source: 'BRRI', sourceUrl: 'http://www.brri.gov.bd',
  },

  // ─── APPLE (4 classes) ───────────────────────────────────────
  {
    id: 'pv_apple_scab',
    cropName: 'Apple', cropNameBn: 'আপেল',
    diseaseName: 'Apple Scab', diseaseNameBn: 'আপেল স্ক্যাব',
    className: 'Apple___Apple_scab', isHealthy: false,
    symptoms: ['Olive-green to black velvety spots on leaves', 'Scabby, corky lesions on fruit', 'Severe defoliation and fruit cracking'],
    symptomsBn: ['পাতায় জলপাই-সবুজ থেকে কালো মখমলি দাগ', 'ফলে খোসপাঁচড়াযুক্ত, কর্কি ক্ষত', 'মারাত্মক পাতা ঝরা ও ফল ফেটে যাওয়া'],
    cause: 'Venturia inaequalis fungus', causeBn: 'ভেন্টুরিয়া ইনাইকোয়ালিস ছত্রাক',
    treatment: ['Apply Captan or Mancozeb during infection periods', 'Myclobutanil for curative action'],
    treatmentBn: ['সংক্রমণ সময়ে ক্যাপটান বা ম্যানকোজেব প্রয়োগ', 'প্রতিকারমূলক পদক্ষেপে মাইক্লোবিউটানিল'],
    prevention: ['Plant scab-resistant varieties', 'Remove fallen leaves in autumn', 'Prune for good air circulation'],
    preventionBn: ['স্ক্যাব-প্রতিরোধী জাত চাষ', 'শরৎকালে ঝরা পাতা সরান', 'বায়ু চলাচলের জন্য ছাঁটাই'],
    severity: 'high', source: 'PlantVillage', sourceUrl: 'https://plantvillage.psu.edu/topics/apple/infos',
  },
  {
    id: 'pv_apple_black_rot',
    cropName: 'Apple', cropNameBn: 'আপেল',
    diseaseName: 'Black Rot', diseaseNameBn: 'কালো পচন',
    className: 'Apple___Black_rot', isHealthy: false,
    symptoms: ['Purple-bordered brown spots on leaves (frog-eye leaf spot)', 'Large brown rotting area on fruit starting from calyx end', 'Cankers on limbs and trunk'],
    symptomsBn: ['পাতায় বেগুনি সীমানাযুক্ত বাদামী দাগ', 'ফলে বোটার দিক থেকে বড় বাদামী পচন', 'ডাল ও কাণ্ডে ক্যাঙ্কার'],
    cause: 'Botryosphaeria obtusa fungus', causeBn: 'বট্রিওস্ফেরিয়া ওবটুসা ছত্রাক',
    treatment: ['Prune and burn cankered branches', 'Apply Captan or Thiophanate-methyl', 'Remove mummified fruit'],
    treatmentBn: ['ক্যাঙ্কারযুক্ত ডাল ছেঁটে পুড়িয়ে ফেলুন', 'ক্যাপটান বা থায়োফ্যানেট-মিথাইল প্রয়োগ', 'শুকিয়ে যাওয়া ফল সরান'],
    prevention: ['Remove dead wood and mummies', 'Maintain tree vigor', 'Fungicide program'],
    preventionBn: ['মরা কাঠ ও শুকনো ফল সরান', 'গাছের শক্তি বজায় রাখুন', 'ছত্রাকনাশক কর্মসূচি'],
    severity: 'high', source: 'PlantVillage', sourceUrl: 'https://plantvillage.psu.edu/topics/apple/infos',
  },
  {
    id: 'pv_apple_cedar_rust',
    cropName: 'Apple', cropNameBn: 'আপেল',
    diseaseName: 'Cedar Apple Rust', diseaseNameBn: 'সিডার আপেল রাস্ট',
    className: 'Apple___Cedar_apple_rust', isHealthy: false,
    symptoms: ['Bright orange-yellow spots on upper leaf surface', 'Tube-like structures (aecia) on lower leaf surface', 'Spots on fruit'],
    symptomsBn: ['পাতার উপরিভাগে উজ্জ্বল কমলা-হলুদ দাগ', 'পাতার নিচে নলের মতো গঠন (এসিয়া)', 'ফলে দাগ'],
    cause: 'Gymnosporangium juniperi-virginianae fungus', causeBn: 'জিমনোস্পোরেঞ্জিয়াম ছত্রাক',
    treatment: ['Apply Myclobutanil at pink bud stage', 'Remove nearby juniper/cedar trees if possible'],
    treatmentBn: ['গোলাপি কুঁড়ি পর্যায়ে মাইক্লোবিউটানিল প্রয়োগ', 'সম্ভব হলে কাছের জুনিপার/সিডার গাছ সরান'],
    prevention: ['Plant rust-resistant varieties', 'Remove alternate host (junipers) within 1-2 miles'],
    preventionBn: ['রাস্ট-প্রতিরোধী জাত চাষ', '১-২ মাইলের মধ্যে বিকল্প হোস্ট (জুনিপার) সরান'],
    severity: 'moderate', source: 'PlantVillage', sourceUrl: 'https://plantvillage.psu.edu/topics/apple/infos',
  },
  {
    id: 'pv_apple_healthy',
    cropName: 'Apple', cropNameBn: 'আপেল',
    diseaseName: 'Healthy', diseaseNameBn: 'সুস্থ',
    className: 'Apple___healthy', isHealthy: true,
    symptoms: ['No disease symptoms'], symptomsBn: ['কোনো রোগের লক্ষণ নেই'],
    cause: 'N/A', causeBn: 'প্রযোজ্য নয়',
    treatment: ['Continue standard management'], treatmentBn: ['মানসম্মত পরিচর্যা চালিয়ে যান'],
    prevention: ['Regular scouting'], preventionBn: ['নিয়মিত পরিদর্শন'],
    severity: 'low', source: 'PlantVillage', sourceUrl: 'https://plantvillage.psu.edu/topics/apple/infos',
  },

  // ─── GRAPE (4 classes) ───────────────────────────────────────
  {
    id: 'pv_grape_black_rot',
    cropName: 'Grape', cropNameBn: 'আঙুর',
    diseaseName: 'Black Rot', diseaseNameBn: 'কালো পচন',
    className: 'Grape___Black_rot', isHealthy: false,
    symptoms: ['Brown circular lesions on leaves with dark border', 'Fruit shrivels into hard black mummies', 'Lesions on shoots and tendrils'],
    symptomsBn: ['পাতায় গাঢ় সীমানাযুক্ত বাদামী গোলাকার ক্ষত', 'ফল কুঁচকে কালো শক্ত মমি হয়ে যায়', 'কচি ডাল ও আকর্ষে ক্ষত'],
    cause: 'Guignardia bidwellii fungus', causeBn: 'গুইগন্যার্ডিয়া বিডওয়েলি ছত্রাক',
    treatment: ['Apply Mancozeb or Myclobutanil from bud break', 'Remove and destroy mummified fruit'],
    treatmentBn: ['কুঁড়ি ভাঙা থেকে ম্যানকোজেব বা মাইক্লোবিউটানিল প্রয়োগ', 'শুকিয়ে যাওয়া ফল সরিয়ে ধ্বংস'],
    prevention: ['Good canopy management for air flow', 'Remove mummies and infected debris', 'Timely fungicide applications'],
    preventionBn: ['বায়ু চলাচলের জন্য ভালো ক্যানোপি ব্যবস্থাপনা', 'মমি ও আক্রান্ত ধ্বংসাবশেষ সরান', 'সময়মতো ছত্রাকনাশক প্রয়োগ'],
    severity: 'high', source: 'PlantVillage', sourceUrl: 'https://plantvillage.psu.edu/topics/grape/infos',
  },
  {
    id: 'pv_grape_esca',
    cropName: 'Grape', cropNameBn: 'আঙুর',
    diseaseName: 'Esca (Black Measles)', diseaseNameBn: 'এস্কা (কালো হাম)',
    className: 'Grape___Esca_(Black_Measles)', isHealthy: false,
    symptoms: ['Tiger-striped pattern on leaves (interveinal chlorosis and necrosis)', 'Dark spots on berries', 'Sudden wilting and death of vine (apoplexy form)'],
    symptomsBn: ['পাতায় বাঘের ডোরাকাটা প্যাটার্ন', 'বেরিতে গাঢ় দাগ', 'লতা হঠাৎ মুরঝে যাওয়া ও মৃত্যু'],
    cause: 'Complex of fungi (Phaeomoniella, Phaeoacremonium, Fomitiporia)',
    causeBn: 'ছত্রাকের জটিল সমষ্টি',
    treatment: ['No effective chemical control', 'Trunk surgery for infected wood', 'Remedial surgery cutting back to healthy wood'],
    treatmentBn: ['কোনো কার্যকর রাসায়নিক নিয়ন্ত্রণ নেই', 'আক্রান্ত কাঠের জন্য কাণ্ড অস্ত্রোপচার', 'সুস্থ কাঠ পর্যন্ত কেটে ফেলা'],
    prevention: ['Protect pruning wounds with wound sealant', 'Avoid large pruning cuts', 'Use clean planting material'],
    preventionBn: ['ছাঁটাই ক্ষতে সিলান্ট দিয়ে সুরক্ষা', 'বড় ছাঁটাই কাটা এড়িয়ে চলুন', 'পরিষ্কার রোপণ উপাদান ব্যবহার'],
    severity: 'critical', source: 'PlantVillage', sourceUrl: 'https://plantvillage.psu.edu/topics/grape/infos',
  },

  // ─── BRINJAL / EGGPLANT (Bangladesh-specific) ─────────────────
  {
    id: 'bd_brinjal_fruit_shoot_borer',
    cropName: 'Brinjal (Eggplant)', cropNameBn: 'বেগুন',
    diseaseName: 'Fruit & Shoot Borer', diseaseNameBn: 'ফল ও কাণ্ড ছিদ্রকারী পোকা',
    className: 'Brinjal___Fruit_Shoot_Borer', isHealthy: false,
    symptoms: ['Wilting and drooping of young shoots', 'Bore holes in shoots with frass', 'Bore holes in fruit with internal feeding damage', 'Fruit becomes unmarketable'],
    symptomsBn: ['কচি ডাল ঢলে পড়া ও মুরঝানো', 'ডালে ছিদ্র ও মলের উপস্থিতি', 'ফলে ছিদ্র ও অভ্যন্তরীণ খাওয়ার ক্ষতি', 'ফল বাজারজাত অযোগ্য'],
    cause: 'Leucinodes orbonalis (Eggplant Fruit and Shoot Borer moth)',
    causeBn: 'লিউসিনোডেস অরবোনালিস (বেগুনের ফল ও কাণ্ড ছিদ্রকারী মথ)',
    treatment: ['Install pheromone traps (4/bigha)', 'Spray Emamectin Benzoate 5SG (0.4g/L)', 'Remove and destroy infested shoots/fruit weekly'],
    treatmentBn: ['ফেরোমন ফাঁদ স্থাপন (৪টি/বিঘা)', 'ইমামেক্টিন বেনজয়েট ৫SG (০.৪গ্রা/লি) স্প্রে', 'প্রতি সপ্তাহে আক্রান্ত ডাল/ফল সরিয়ে ধ্বংস করুন'],
    prevention: ['Use Bt Brinjal varieties (BARI Bt Begun-1/2/3/4)', 'Clip and destroy wilted shoots regularly', 'Avoid continuous brinjal cultivation'],
    preventionBn: ['Bt বেগুন জাত ব্যবহার করুন (BARI Bt বেগুন-১/২/৩/৪)', 'নিয়মিত মুরঝানো ডাল কেটে ধ্বংস করুন', 'একটানা বেগুন চাষ পরিহার'],
    severity: 'high', source: 'BARI Bt Begun Technology Guide', sourceUrl: 'https://www.bari.gov.bd',
  },

  // ─── WHEAT (Bangladesh-specific) ──────────────────────────────
  {
    id: 'bd_wheat_blast',
    cropName: 'Wheat', cropNameBn: 'গম',
    diseaseName: 'Wheat Blast', diseaseNameBn: 'গম ব্লাস্ট',
    className: 'Wheat___Blast', isHealthy: false,
    symptoms: ['Bleaching/whitening of spike above point of infection', 'Gray-brown lesion at rachis node', 'Shriveled/empty grains', 'Leaf lesions similar to rice blast'],
    symptomsBn: ['সংক্রমণ বিন্দুর উপরে শীষ সাদা/বিবর্ণ হওয়া', 'র‍্যাকিস নোডে ধূসর-বাদামী ক্ষত', 'কুঁচকানো/খালি দানা', 'ধানের ব্লাস্টের মতো পাতার ক্ষত'],
    cause: 'Magnaporthe oryzae pathotype Triticum (MoT)',
    causeBn: 'ম্যাগন্যাপোর্থি ওরাইজি প্যাথোটাইপ ট্রিটিকাম',
    treatment: ['No fully effective fungicide after infection', 'Preventive Tebuconazole + Trifloxystrobin at heading', 'Destroy crop residue completely'],
    treatmentBn: ['সংক্রমণের পর সম্পূর্ণ কার্যকর ছত্রাকনাশক নেই', 'শীষ বের হওয়ার সময় প্রতিরোধমূলক টেবুকোনাজল + ট্রাইফ্লক্সিস্ট্রোবিন', 'ফসলের অবশিষ্ট সম্পূর্ণ ধ্বংস'],
    prevention: ['Use blast-resistant varieties (BARI Gom-33 BARI Gom-30)', 'Avoid late sowing (after 30 Nov)', 'Seed treatment with Carboxin + Thiram'],
    preventionBn: ['ব্লাস্ট-প্রতিরোধী জাত ব্যবহার (BARI গম-৩৩, BARI গম-৩০)', 'দেরিতে বপন (৩০ নভেম্বরের পর) পরিহার', 'কার্বোক্সিন + থিরাম দিয়ে বীজ শোধন'],
    severity: 'critical', source: 'BWMRI / BARI', sourceUrl: 'https://www.bari.gov.bd',
  },
];

// Utility: find best matching disease record by name
export function findDiseaseByName(name: string): DiseaseRecord | undefined {
  const lower = name.toLowerCase().trim();
  return PLANT_DISEASES.find(d =>
    d.diseaseName.toLowerCase() === lower ||
    d.className.toLowerCase().replace(/_/g, ' ').includes(lower) ||
    lower.includes(d.diseaseName.toLowerCase())
  );
}

// All unique crop names in the KB
export const DISEASE_CROPS = [...new Set(PLANT_DISEASES.map(d => d.cropName))];

// Count of non-healthy disease classes
export const DISEASE_COUNT = PLANT_DISEASES.filter(d => !d.isHealthy).length;
export const TOTAL_CLASSES = PLANT_DISEASES.length;
